# Generated by Django 4.2.2 on 2023-07-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_autor', models.CharField(max_length=20)),
                ('apellido_autor', models.CharField(max_length=20)),
                ('titulo_poema', models.CharField(max_length=20)),
                ('fecha_publicacion', models.DateField()),
            ],
        ),
    ]
