# Generated by Django 4.2.2 on 2023-07-17 22:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=20)),
                ('contenido', ckeditor.fields.RichTextField()),
                ('fecha_publicacion', models.DateField(null=True)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas')),
            ],
        ),
    ]
