# Generated by Django 4.2.2 on 2023-07-15 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_poema_portada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poema',
            old_name='apellido_autor',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='poema',
            old_name='nombre_autor',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='poema',
            name='titulo_poema',
        ),
    ]
