# Generated by Django 4.2.2 on 2023-07-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_rename_apellido_autor_poema_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poema',
            name='fecha_publicacion',
            field=models.DateField(null=True),
        ),
    ]
